name: friendship
description: Using Advanced Digital Technology to Develop Real Life Human Connections.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  google_fonts: ^1.1.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_launcher_icons: "^0.8.0"
  flutter_test:
    sdk: flutter
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/NoahsArkIcon.png"

flutter:
  uses-material-design: true

  assets:
    - images/NoahsArkIcon.png

